
export default {
	newGroups: [
		{
			name: "ORTC (Object Real-time Communications) Community Group",
			identifier: "cg/ortc",
			homepage: "https://www.w3.org/community/ortc/",
		},
		{
			name: "Media Resource In-band Tracks Community Group",
			identifier: "cg/inbandtracks",
			homepage: "https://www.w3.org/community/inbandtracks/",
		},
		{
			name: "XSLT Working Group",
			identifier: "wg/xslt",
			homepage: "https://www.w3.org/Style/XSL/",
		},
		{
			name: "XML Query Working Group",
			identifier: "wg/xml-query",
			homepage: "https://www.w3.org/XML/Query/",
		},
		{
			name: "XML Core Working Group",
			identifier: "wg/xml-core",
			homepage: "https://www.w3.org/XML/Core/",
		},
		{
			name: "Tracking Protection Working Group",
			identifier: "wg/tracking",
			homepage: "https://www.w3.org/2011/tracking-protection/",
		},

		{
			name: "Web Hypertext Application Technology Working Group",
			identifier: "whatwg",
			homepage: "https://whatwg.org/",
		},
		{
			name: "TC39",
			identifier: "tc39",
			homepage: "https://tc39.es/",
		},
		{
			name: "WebGL Working Groups",
			identifier: "khronos/webglwg",
			homepage: "https://www.khronos.org/",
		},
		{
			name: "Alliance for Open Media",
			identifier: "aomedia",
			homepage: "https://aomedia.org/",
		},
		{
			name: "IETF Web Packaging Working Group",
			identifier: "ietf/wpack",
			homepage: "https://datatracker.ietf.org/wg/wpack/about/",
		},
		{
			name: "Ben Wiser",
			identifier: "benwiser",
			homepage: "https://github.com/RupertBenWiser",
		},
		{
			name: "Chase Phillips",
			identifier: "chasephillips",
			homepage: "https://github.com/chasephillips",
		},
		{
			name: "Tab Atkins",
			identifier: "tabatkins",
			homepage: "https://github.com/tabatkins",
		},
		{
			name: "Harald Alvestrand",
			identifier: "haraldalvestrand",
			homepage: "https://github.com/alvestrand",
		},
		{
			name: "Google",
			identifier: "google",
			homepage: "https://developers.google.com/web",
		},
		{
			name: "Mozilla",
			identifier: "mozilla",
			homepage: "https://www.mozilla.org/en-US/about/",
		},
		{
			name: "DeWitt Clinton",
			identifier: "dewittclinton",
			homepage: "https://github.com/dewitt",
		},
		{
			name: "David Baron",
			identifier: "davidbaron",
			homepage: "https://github.com/dbaron",
		},
		{
			name: "FIDO Alliance",
			identifier: "fidoalliance",
			homepage: "https://fidoalliance.org/",
		},
		{
			name: "Netscape",
			identifier: "netscape",
			homepage: "https://connect.netscape.com/",
		},
		{
			name: "CompuServe",
			identifier: "compuserve",
			homepage: "https://www.compuserve.com/",
		},
		{
			name: "Joint Photographic Experts Group",
			identifier: "jpeg",
			homepage: "https://jpeg.org/about.html",
		},
		{
			name: "Moving Picture Experts Group",
			identifier: "mpeg",
			homepage: "https://www.mpeg.org/",
		},
	],
	groupNameRewrites: {
		"Compatibility Workstream": "Web Hypertext Application Technology Working Group",
		"Console Workstream": "Web Hypertext Application Technology Working Group",
		"DOM Workstream": "Web Hypertext Application Technology Working Group",
		"Encoding Workstream": "Web Hypertext Application Technology Working Group",
		"Fetch Workstream": "Web Hypertext Application Technology Working Group",
		"Fullscreen API Workstream": "Web Hypertext Application Technology Working Group",
		"HTML Workstream": "Web Hypertext Application Technology Working Group",
		"Infra Workstream": "Web Hypertext Application Technology Working Group",
		"MIME Sniffing Workstream": "Web Hypertext Application Technology Working Group",
		"Notifications API Workstream": "Web Hypertext Application Technology Working Group",
		"Quirks Mode Workstream": "Web Hypertext Application Technology Working Group",
		"Storage Workstream": "Web Hypertext Application Technology Working Group",
		"Streams Workstream": "Web Hypertext Application Technology Working Group",
		"Test Utils Workstream": "Web Hypertext Application Technology Working Group",
		"URL Workstream": "Web Hypertext Application Technology Working Group",
		"Web IDL Workstream": "Web Hypertext Application Technology Working Group",
		"XMLHttpRequest Workstream": "Web Hypertext Application Technology Working Group",
	},
	newSpecs: [
		{ repo: "https://github.com/w3c/audio-session", group: "wg/media" },
		{ repo: "https://github.com/w3c/editing/tree/gh-pages/docs/execCommand", group: "wg/webediting" },
		{ repo: "https://github.com/w3c/mathml", group: "wg/math" },
		{ repo: "https://github.com/w3c/mediacapture-extensions", group: "wg/webrtc" },
		{ repo: "https://github.com/w3c/mediacapture-handle/tree/main/actions", group: "wg/webrtc" },
		{ repo: "https://github.com/w3c/mse-byte-stream-format-registry", group: "wg/media" },
		{ repo: "https://github.com/w3c/mse-byte-stream-format-isobmff", group: "wg/media" },
		{ repo: "https://github.com/w3c/mse-byte-stream-format-mp2t", group: "wg/media" },
		{ repo: "https://github.com/w3c/mse-byte-stream-format-mpeg-audio", group: "wg/media" },
		{ repo: "https://github.com/w3c/mse-byte-stream-format-webm", group: "wg/media" },
		{ repo: "https://github.com/w3c/webappsec-cowl", group: "wg/webappsec" },
		{ repo: "https://github.com/w3c/webappsec-suborigins", group: "wg/webappsec" },
		{ repo: "https://github.com/w3c/webappsec-uisecurity", group: "wg/webappsec" },
		{ repo: "https://github.com/w3c/webrtc-extensions", group: "wg/webrtc" },
		{ repo: "https://github.com/w3c/webrtc-provisional-stats", group: "wg/webrtc" },
		{ repo: "https://github.com/w3c/xml-entities", group: "wg/math" },
		{ repo: "https://github.com/w3c/dpub-aria", group: "wg/aria" },
		{ repo: "https://github.com/w3c/dpub-aam", group: "wg/aria" },
		{ repo: "https://github.com/w3c/webpayments-crypto", group: "wg/payments" },
		{ repo: "https://github.com/w3c/webpayments-http-messages", group: "wg/payments" },
		{ repo: "https://github.com/w3c/webpayments-methods-tokenization", group: "wg/payments" },
		{ repo: "https://github.com/w3c/p2p-webtransport", group: "cg/ortc" },
		{ repo: "https://github.com/w3c/p2p-webtransport/blob/master/cs.html", group: "cg/ortc" },
		{ repo: "https://github.com/w3c/ortc", url: "https://draft.ortc.org/", group: "cg/ortc" },
		{ repo: "https://github.com/w3c/merchant-validation", group: "wg/payments" },
		{ repo: "https://github.com/WICG/WebApiDevice/tree/main/managed_config", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/WebApiDevice/tree/main/device_attributes", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/overscroll-scrollend-events", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/aom/tree/gh-pages/spec", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/aom/blob/gh-pages/spec/aria-reflection.bs", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/aom/blob/gh-pages/spec/custom-element-semantics.bs", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/aom/spec/input-events.html", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/conditional-focus", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/handwriting-recognition", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/multicapture", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/nav-speculation/blob/main/no-vary-search.bs", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/pending-beacon", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/visual-viewport", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/web-smart-card", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/webpackage/subresource-loading.html", group: "ietf/wpack" },
		{ repo: "https://github.com/WICG/webpackage/blob/main/draft-yasskin-dispatch-web-packaging.md", group: "ietf/wpack" },
		{ repo: "https://github.com/WICG/webpackage/blob/main/draft-yasskin-http-origin-signed-responses.md", group: "ietf/wpack" },
		{ repo: "https://github.com/WICG/webpackage/blob/main/draft-yasskin-httpbis-origin-signed-exchanges-impl.md", group: "ietf/wpack" },
		{ repo: "https://github.com/WICG/anonymous-iframe", group: "cg/wicg" },
		{ repo: "https://github.com/WICG/webmonetization", url: "https://webmonetization.org/specification/", group: "cg/wicg" },
		{ repo: "https://github.com/webmachinelearning/model-loader", group: "cg/webmachinelearning" },
		{ repo: "https://github.com/wpack-wg/bundled-responses/blob/main/draft-ietf-wpack-bundled-responses.md", group: "ietf/wpack" },
		{ repo: "https://github.com/WebBluetoothCG/web-bluetooth/blob/main/scanning.html", group: "cg/web-bluetooth" },
		{ repo: "https://github.com/tc39/proposal-import-attributes", url: "https://tc39.es/proposal-import-attributes/", group: "tc39" },
		{ repo: "https://github.com/patcg-individual-drafts/topics", group: "cg/patcg" },
		{ repo: "https://github.com/patcg-individual-drafts/private-aggregation-api", group: "cg/patcg" },
		{ repo: "https://github.com/immersive-web/marker-tracking", group: "cg/immersive-web" },
		{ repo: "https://github.com/immersive-web/real-world-geometry/blob/main/webxrmeshing-1.bs", group: "cg/immersive-web" },
		{ repo: "https://github.com/immersive-web/real-world-geometry/blob/main/plane-detection.bs", group: "cg/immersive-web" },
		{ repo: "https://github.com/screen-share/capture-all-screens", group: "cg/sccg" },
		{ repo: "https://github.com/RupertBenWiser/Web-Environment-Integrity", group: "benwiser" },
		{ repo: "https://github.com/WICG/color-api", group: "cg/wicg" },
		{ repo: "https://github.com/chasephillips/controlled-frame", group: "chasephillips" },
		{ repo: "https://github.com/AOMediaCodec/av1-hdr10plus", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/av1-isobmff", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/av1-spec", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/av1-mpeg2-ts", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/av1-avif", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/av1-rtp-spec", group: "aomediacodec" },
		{ repo: "https://github.com/AOMediaCodec/afgs1-spec", group: "aomediacodec" },
		{ repo: "https://github.com/tabatkins/css-toggle", group: "tabatkins" },
		{ repo: "https://github.com/tabatkins/specs/tree/gh-pages/css-stacking-context-1", group: "tabatkins" },
		{ repo: "https://github.com/w3c/permissions-registry", group: "wg/webappsec" },
		{ repo: "https://github.com/alvestrand/mediacapture-transform/tree/chrome-96", url: "https://alvestrand.github.io/mediacapture-transform/chrome-96.html", group: "haraldalvestrand" },
		{ repo: null, url: "https://developers.google.com/speed/webp/docs/riff_container", group: "google" },
		{ repo: null, url: "https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification", group: "google" },
		{ repo: "https://github.com/googlefonts/colr-gradients-spec/blob/main/OFF_AMD2_WD.md", url: "https://github.com/googlefonts/colr-gradients-spec/blob/main/OFF_AMD2_WD.md", group: "google" },
		{ repo: "https://github.com/w3c/HTMLSourcingInbandTracks", url: "https://dev.w3.org/html5/html-sourcing-inband-tracks/", group: "cg/inbandtracks" },
		{ repo: "https://github.com/w3c/svgwg/tree/main/specs/streaming", url: "https://svgwg.org/specs/streaming/", group: "wg/svg" },
		{ repo: "https://github.com/w3c/svgwg/tree/main/specs/markers", url: "https://svgwg.org/specs/markers/", group: "wg/svg" },
		{ repo: null, url: "https://wiki.mozilla.org/APNG_Specification", group: "mozilla" },
		{ repo: "https://github.com/w3c/css-houdini-drafts/tree/main/box-tree-api", url: "https://drafts.css-houdini.org/box-tree-api-1/", group: "wg/css" },
		{ repo: null, url: "https://www.w3.org/TR/xml11/", group: "wg/xml-core" },
		{ repo: null, url: "https://www.w3.org/TR/xml-names11/", group: "wg/xml-core" },
		{ repo: null, url: "https://www.w3.org/TR/xslt-30/", group: "wg/xslt" },
		{ repo: null, url: "https://www.w3.org/TR/xpath-31/", group: "wg/xml-query" },
		{ repo: "https://github.com/KhronosGroup/OpenGL-Registry/tree/main/specs/es/3.2", url: "https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html", group: "khronos" },
		{ repo: "https://github.com/KhronosGroup/glTF-Registry/tree/main/specs/2.0", url: "https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html", group: "khronos" },
		{ repo: "https://github.com/dewitt/opensearch", url: "https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md", group: "dewittclinton" },
		{ repo: "https://github.com/tc39/source-map-spec", url: "https://tc39.es/source-map-spec/", group: "tc39" },
		{ repo: "https://github.com/dbaron/css-intrinsic-isize-props", group: "davidbaron" },
		{ repo: "https://github.com/dbaron/css-intrinsic-sizing-one-axis", group: "davidbaron" },
		{ repo: null, url: "https://dbaron.org/css/intrinsic/", group: "davidbaron" },
		{ repo: null, url: "https://nokiatech.github.io/heif/technical.html", group: "mpeg" },
		// { repo: null, url: "https://ijg.org/files/T-REC-T.871-201105-I!!PDF-E.pdf", group: "jpeg" },
		// { repo: null, url: "https://ijg.org/files/Wallace.JPEG.pdf", group: "jpeg" },
		{ repo: null, url: "https://www.w3.org/Graphics/JPEG/jfif3.pdf", group: "jpeg" },
		{ repo: null, url: "https://www.w3.org/Graphics/JPEG/itu-t81.pdf", group: "jpeg" },
		{ repo: null, url: "https://www.w3.org/Graphics/GIF/spec-gif87.txt", group: "compuserve" },
		{ repo: null, url: "https://www.w3.org/Graphics/GIF/spec-gif89a.txt", group: "compuserve" },
		{ repo: null, url: "http://www.vurdalakov.net/misc/gif/netscape-looping-application-extension/", group: "netscape" },
		// TODO: more FIDO specs at https://fidoalliance.org/specs/
		// TODO: more image, audio, video, font, ... formats
	],
	titleRewrites: {
		"jpeg": {
			"https://www.w3.org/Graphics/JPEG/jfif3.pdf": "JPEG File Interchange Format",
			"https://www.w3.org/Graphics/JPEG/itu-t81.pdf": "Digital compression and coding of continuous-tone still images",
		},
		"compuserve": {
			"https://www.w3.org/Graphics/GIF/spec-gif87.txt": "Graphics Interchange Format (GIF) version 87a",
			"https://www.w3.org/Graphics/GIF/spec-gif89a.txt": "Graphics Interchange Format (GIF) version 89a",
		},
	}
};
