
export default {
	excludedGroups: [
		"bg/autowebplatform",
		"bg/publishingbg",
		"bg/web-adv",
		"cg/a11y-discov-vocab",
		"cg/a11yedge",
		"cg/accessibility4children",
		"cg/accesslearn",
		"cg/act-r",
		"cg/aikr",
		"cg/antifraud",
		"cg/applied-did-and-vc",
		"cg/architypes",
		"cg/argumentation",
		"cg/aria-at",
		"cg/atomic-data",
		"cg/audio-comgp",
		"cg/audio-description",
		"cg/av4browsers",
		"cg/bdns",
		"cg/bibframe2schema",
		"cg/bioschemas",
		"cg/bitcoin",
		"cg/bits",
		"cg/blockchain",
		"cg/bpmlod",
		"cg/chem-web-pub",
		"cg/civics",
		"cg/cns",
		"cg/coga-community",
		"cg/cogai",
		"cg/colorweb",
		"cg/consent",
		"cg/conv",
		"cg/council",
		"cg/credentials",
		"cg/credibility",
		"cg/css4",
		"cg/cssprint",
		"cg/csvw",
		"cg/cv3",
		"cg/datavis",
		"cg/dcdr-framework",
		"cg/declarative3d",
		"cg/decsharing",
		"cg/design-tokens",
		"cg/digitalassetmanagement",
		"cg/dpvcg",
		"cg/eocred-schema",
		"cg/epub3",
		"cg/equity",
		"cg/exercises-and-activities",
		"cg/expath",
		"cg/fed-id",
		"cg/federated-learning",
		"cg/fibo",
		"cg/font-text",
		"cg/foss-3d",
		"cg/games",
		"cg/gao",
		"cg/hclscg",
		"cg/html-dynamic-extensions",
		"cg/html5spec",
		"cg/htmlvoc",
		"cg/humancentricai",
		"cg/humanservices",
		"cg/hydra",
		"cg/immersive-captions",
		"cg/informationarchitecture",
		"cg/inter-cc",
		"cg/interledger",
		"cg/iotschema",
		"cg/ixml",
		"cg/json-ld",
		"cg/kg-construct",
		"cg/lbd",
		"cg/ld4lt",
		"cg/ldpnext",
		"cg/low-vision",
		"cg/maps4html",
		"cg/mathml4",
		"cg/md-odrl-profile",
		"cg/metaverse-interop",
		"cg/miniapps",
		"cg/mixedreality",
		"cg/ml-schema",
		"cg/multicast",
		"cg/music-notation",
		"cg/n3-dev",
		"cg/nordic-accessibility",
		"cg/nordic-data",
		"cg/nostr",
		"cg/odrl",
		"cg/oerschema",
		"cg/ontolex",
		"cg/openactive",
		"cg/opentag",
		"cg/opentrack",
		"cg/pair-cg",
		"cg/perma-id",
		"cg/philoweb",
		"cg/planning",
		"cg/publishingcg",
		"cg/pwe",
		"cg/quickfix",
		"cg/rdf-dev",
		"cg/rdf-tests",
		"cg/rdfjs",
		"cg/rdfsurfaces",
		"cg/reconciliation",
		"cg/rosc",
		"cg/rsp",
		"cg/rtie",
		"cg/rww",
		"cg/schema-course-extend",
		"cg/schemabibex",
		"cg/schemaorg",
		"cg/schemaorg4datasets",
		"cg/schemed",
		"cg/scholarlyhtml",
		"cg/semind",
		"cg/sentiment",
		"cg/service-disco",
		"cg/shacl",
		"cg/shex",
		"cg/smartcity-nordic",
		"cg/socialcg",
		"cg/solid",
		"cg/sparql-12",
		"cg/speced-cg",
		"cg/sport-schema",
		"cg/sustainability",
		"cg/sustyweb",
		"cg/sync-media-pub",
		"cg/talent-signal",
		"cg/tdmrep",
		"cg/timesh",
		"cg/tourismdata",
		"cg/treecg",
		"cg/unhosted",
		"cg/voiceinteraction",
		"cg/w3process",
		"cg/wai-engage",
		"cg/web-thing-protocol",
		"cg/webagents",
		"cg/webassembly",
		"cg/webauthn-adoption",
		"cg/webcomponents",
		"cg/webdx",
		"cg/webextensions",
		"cg/webhistory",
		"cg/webid",
		"cg/webmediaapi",
		"cg/webscreens",
		"cg/webtiming",
		"cg/webview",
		"cg/webvmt-cg",
		"cg/wintercg",
		"cg/wot",
		"cg/wot-jp",
		"cg/xapivocabulary",
		"cg/xformsusers",
		"cg/xproc-next",
		"cg/xslt-40",
		"cg/zot",
		"ig/chinese-web",
		"ig/i18n",
		"ig/me",
		"ig/privacy",
		"ig/psig",
		"ig/securepay",
		"ig/wai",
		"ig/web-networks",
		"ig/wot",
		"other/ab",
		"other/ac",
		"other/board",
		"other/tag",
		"tf/aria-editors",
		"tf/aria-practices",
		"tf/auto-privacy-security",
		"tf/automotive-pay",
		"tf/board-directors",
		"tf/board-finance",
		"tf/board-governance",
		"tf/board-personnel",
		"tf/cognitive-a11y-tf",
		"tf/dx-dcat",
		"tf/fast",
		"tf/i18n-afrlreq",
		"tf/i18n-alreq",
		"tf/i18n-clreq",
		"tf/i18n-elreq",
		"tf/i18n-eurlreq",
		"tf/i18n-hlreq",
		"tf/i18n-jlreq",
		"tf/i18n-mlreq",
		"tf/i18n-sealreq",
		"tf/i18n-tlreq",
		"tf/iip",
		"tf/low-vision-a11y-tf",
		"tf/maturity",
		"tf/mobile-a11y-tf",
		"tf/personalization-tf",
		"tf/pmchairs",
		"tf/pronunciation-tf",
		"tf/publ-sc",
		"tf/rch-wg-chairs",
		"tf/rdf-star-chairs",
		"tf/rdf-star-editors",
		"tf/rdf-star-semantics",
		"tf/rdf-star-ucr",
		"tf/rqtf",
		"tf/svg-a11y",
		"tf/tag-privacy",
		"tf/transportation-ont-cc",
		"tf/vc-wg-chairs",
		"tf/vision",
		"tf/wcag-act",
		"tf/wcag2ict",
		"wg/apa",
		"wg/auto",
		"wg/css",
		"wg/distributed-tracing",
		"wg/dx",
		"wg/eowg",
		"wg/gpu",
		"wg/htmlwg",
		"wg/i18n-core",
		"wg/json-ld",
		"wg/miniapps",
		"wg/pm",
		"wg/rch",
		"wg/rdf-star",
		"wg/sdw",
		"wg/svg",
		"wg/timed-text",
		"wg/vc",
		"wg/wot",
	],
	additionalGroups: [
		{
			name: "Khronos Group",
			identifier: "khronos",
			homepage: "https://www.khronos.org/",
		},
		{
			name: "Alliance for Open Media",
			identifier: "aomedia",
			homepage: "https://aomedia.org/",
		},
	],
	excludedRepos: {
		"wg/css": [
			"https://github.com/w3c/csswg-drafts/tree/main/css-egg-1",
		],
		"fxtf": [
			"https://github.com/w3c/fxtf-drafts/tree/main/custom",
			"https://github.com/w3c/fxtf-drafts/tree/main/matrix",
		],
		"wg/ag": [
			"https://github.com/w3c/wcag-act-rules-cg",
			"https://github.com/w3c/wcag2ict",
		],
		"wg/audio": [
			"https://github.com/WebAudio/Audio-EQ-Cookbook"
		],
		"wg/math": [
			"https://github.com/w3c/mathml-docs",
		],
		"wg/svg": [
			"https://github.com/w3c/writing-accessible-svg"
		],
		// "cg/webassembly": [
		// 	"https://github.com/WebAssembly/annotations",
		// 	"https://github.com/WebAssembly/feature-detection",
		// 	"https://github.com/WebAssembly/profiles",
		// 	"https://github.com/WebAssembly/spec",
		// ],
		"wg/wasm": [
			"https://github.com/w3c/wasm-wg",
		],
		"wg/json-ld": [
			"https://github.com/w3c/json-ld-rc"
		],
		"wg/webapps": [
			"https://github.com/w3c/contact-picker",
		],
		"wg/das": [
			"https://github.com/w3c/wake-lock",
			"https://github.com/w3c/devicesensors-wg",
		],
		"cg/gpu": [
			"https://github.com/gpuweb/cts",
		],
		"wg/gpu": [
			"https://github.com/gpuweb/cts",
		],
		"cg/immersive-web": [
			"https://github.com/immersive-web/webvr-polyfill-dpdb",
			"https://github.com/immersive-web/webxr-input-profiles",
			"https://github.com/immersive-web/geo-alignment",
			"https://github.com/immersive-web/immersive-web-weekly",
			"https://github.com/immersive-web/webvr-polyfill",
			"https://github.com/immersive-web/webxr-layers-polyfill",
		],
		"wg/immersive-web": [
			"https://github.com/immersive-web/immersiveweb.dev",
			"https://github.com/immersive-web/webxr-test-api",
		],
		"tf/silver-tf": [
			"https://github.com/w3c/silver",
		],
		"wg/aria": [
			"https://github.com/w3c/aria-practices",
		],
		"cg/audio-comgp": [
			"https://github.com/WebAudio/Audio-EQ-Cookbook",
		],
		"cg/open-ui": [
			"https://github.com/openui/open-ui",
		],
		"wg/did": [
			"https://github.com/w3c/did-test-suite",
			"https://github.com/w3c/did-use-cases",
		],
		"cg/privacycg": [
			"https://github.com/privacycg/template",
		],
		"wg/webappsec": [
			"https://github.com/w3c/webappsec-cors-for-developers",
		],
		"wg/webfonts": [
			"https://github.com/w3c/IFT",
			"https://github.com/w3c/PFE-analysis",
		],
		"wg/webmachinelearning": [
			"https://github.com/webmachinelearning/webmachinelearning-ethics",
		],
		"wg/payments": [
			"https://github.com/w3c/webpayments",
			"https://github.com/w3c/webpayments-flows",
		],
		"cg/wicg": [
			"https://github.com/WICG/admin",
			"https://github.com/WICG/audio-focus",
			"https://github.com/WICG/capability-delegation",
			"https://github.com/WICG/controls-list",
			"https://github.com/WICG/devtools-protocol",
			"https://github.com/WICG/file-handling",
			"https://github.com/WICG/focus-visible",
			"https://github.com/WICG/import-maps",
			"https://github.com/WICG/inert",
			"https://github.com/WICG/media-latency-hint",
			"https://github.com/WICG/nav-speculation",
			"https://github.com/WICG/navigation-api",
			"https://github.com/WICG/origin-policy",
			"https://github.com/WICG/spatial-navigation",
			"https://github.com/WICG/starter-kit",
			"https://github.com/WICG/view-transitions",
			"https://github.com/WICG/webpackage",
			"https://github.com/WICG/webmonetization",
			"https://github.com/WICG/element-capture",
			"https://github.com/privacycg/CHIPS",
		],
		"whatwg": [
			"https://github.com/whatwg/html",
		],
	},
	includedRepos: {
		"khronos": [
			"https://github.com/KhronosGroup/WebGL/tree/main/specs/latest/1.0",
			"https://github.com/KhronosGroup/WebGL/tree/main/specs/latest/2.0",
		],
		"wg/webediting": [
			"https://github.com/w3c/editing/tree/gh-pages/docs/execCommand",
		],
		"cg/web-bluetooth": [
			"https://github.com/WebBluetoothCG/web-bluetooth",
		],
		"cg/webmachinelearning": [
			"https://github.com/webmachinelearning/model-loader",
		],
		"cg/gpu": [
			"https://github.com/gpuweb/gpuweb/tree/main/wgsl",
		],
		"cg/wicg": [
			"https://github.com/WICG/shape-detection-api/blob/main/text.bs",
			"https://github.com/WICG/capability-delegation/blob/main/spec.bs",
			"https://github.com/WICG/nav-speculation/blob/main/prefetch.bs",
			"https://github.com/WICG/nav-speculation/blob/main/prerendering.bs",
			"https://github.com/WICG/nav-speculation/blob/main/speculation-rules.bs",
			"https://github.com/WICG/nav-speculation/blob/main/no-vary-search.bs",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-dispatch-web-packaging.md",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-http-origin-signed-responses.md",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-httpbis-origin-signed-exchanges-impl.md",
		],
		"cg/privacycg": [
			"https://github.com/privacycg/CHIPS/blob/main/README.md",
		],
		"tf/silver-tf": [
			"https://github.com/w3c/silver/tree/main/guidelines",
		],
		"wg/wasm": [
			"https://github.com/WebAssembly/spec/tree/main/document/core",
			"https://github.com/WebAssembly/spec/tree/main/document/js-api",
			"https://github.com/WebAssembly/spec/tree/main/document/web-api",
		],
		"cg/fedid": [
			"https://github.com/fedidcg/FedCM",
		],
		"wg/webfonts": [
			"https://github.com/w3c/woff/tree/main/woff1/spec/Overview.html"
		],
		"wg/media": [
			"https://github.com/w3c/audio-session",
		],
		"cg/sccg": [
			"https://github.com/screen-share/captured-mouse-events",
			"https://github.com/screen-share/element-capture",
			"https://github.com/screen-share/capture-all-screens",
		],
		"aomedia": [
			"https://github.com/AOMediaCodec/afgs1-spec",
			"https://github.com/AOMediaCodec/av1-hdr10plus",
			"https://github.com/AOMediaCodec/av1-isobmff",
			"https://github.com/AOMediaCodec/av1-spec",
			"https://github.com/AOMediaCodec/av1-mpeg2-ts",
			"https://github.com/AOMediaCodec/av1-avif",
			"https://github.com/AOMediaCodec/av1-rtp-spec",
		],
		"cg/patcg": [
			"https://github.com/patcg-individual-drafts/topics",
			"https://github.com/patcg-individual-drafts/private-aggregation-api",
		],
		"wg/webapps": [
			"https://github.com/w3c/DOM-Parsing",
		],
	},
	ignoreHomepageUrl: {
		"cg/gpu": [
			"https://github.com/gpuweb/gpuweb",
		],
		"cg/wicg": [
			"https://github.com/WICG/storage-buckets",
			"https://github.com/WICG/client-hints-infrastructure",
			"https://github.com/WICG/local-font-access",
			"https://github.com/WICG/responsive-image-client-hints",
			"https://github.com/WICG/shape-detection-api",
			"https://github.com/WICG/urlpattern",
		],
		"wg/math": [
			"https://github.com/w3c/mathml-core",
		],
		"wg/immersive-web": [
			"https://github.com/immersive-web/webxr-ar-module",
			"https://github.com/immersive-web/webxr-gamepads-module",
		],
		"wg/media": [
			"https://github.com/w3c/picture-in-picture",
		],
		"wg/webrtc": [
			"https://github.com/w3c/mediacapture-fromelement",
		],
	},
	urlRewrites: {
		"cg/wicg": {
			"https://github.com/WICG/webmonetization": "https://webmonetization.org/specification",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-dispatch-web-packaging.md": "https://wicg.github.io/webpackage/draft-yasskin-dispatch-web-packaging",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-http-origin-signed-responses.md": "https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses",
			"https://github.com/WICG/webpackage/blob/main/draft-yasskin-httpbis-origin-signed-exchanges-impl.md": "https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl",
			"https://github.com/WICG/csp-next": "https://wicg.github.io/csp-next/scripting-policy",
		},
		"wg/webperf": {
			"https://github.com/w3c/device-memory": "https://www.w3.org/TR/device-memory/",
		},
		"khronos": {
			"https://github.com/KhronosGroup/WebGL/tree/main/specs/latest/1.0": "https://registry.khronos.org/webgl/specs/latest/1.0/",
			"https://github.com/KhronosGroup/WebGL/tree/main/specs/latest/2.0": "https://registry.khronos.org/webgl/specs/latest/2.0/",
		},
		"wg/wasm": {
			"https://github.com/WebAssembly/spec/tree/main/document/core": "https://webassembly.github.io/spec/core/bikeshed/",
			"https://github.com/WebAssembly/spec/tree/main/document/js-api": "https://webassembly.github.io/spec/js-api/",
			"https://github.com/WebAssembly/spec/tree/main/document/web-api": "https://webassembly.github.io/spec/web-api/",
		},
	},
	specsExcludedFromCSS: [
		"https://aomediacodec.github.io/av1-avif/",
		"https://aomediacodec.github.io/av1-isobmff/",
		"https://w3c.github.io/webappsec-upgrade-insecure-requests/",
	],
};
